CREATE TRANSIENT TABLE car (
   id int  NOT NULL,
   name int  COLLATE  'utf8' NOT NULL
)
CLUSTER BY ('name')
STAGE_FILE_FORMAT = (FORMAT_NAME = 'test')
STAGE_COPY_OPTIONS = (ON_ERROR = CONTINUE)
DATA_RETENTION_TIME_IN_DAYS = 10
CHANGE_TRACKING = TRUE
DEFAULT_DDL_COLLATION = 'en';