CREATE TABLE color (
                       color_id INT GENERATED BY DEFAULT AS IDENTITY
                           (START WITH 10 INCREMENT BY 10),
                       color_name VARCHAR NOT NULL
);